name: Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: 'Setup Dependencies'
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
      - run: ls
