name: Fetch Updates

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_ACTION_PUSH_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: 'Setup Dependencies'
        run: yarn
      - name: 'Fetch'
        run: node fetch-latest-updates.js
      - name: 'Regenerate Update Mapping'
        run: yarn run generate-mapping
      - name: 'Print git statuss'
        run: git status
      - name: 'Print git diff'
        run: git diff
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
          commit_message: Add new CDC file
          branch: ${{ github.head_ref }}

          commit_user_name: TheSavior
          commit_user_email: github@eli-white.com
          commit_author: Eli White <github@eli-white.com>
